### ISSUE TITLE
Destacar canales de comunicacion

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/welcome.osweekends.com#18]
![image](https://user-images.githubusercontent.com/5422102/35994635-5a5b7d24-0d11-11e8-9ff6-a79c77376f63.png)
No se leen muy bien, y lo pondria como un link tal vez?

**Comment by Vickysolo** [comment]
¿Los ponemos en negrita?¿o con otro color?

**Comment by UlisesGascon** [comment]
Voto si @Vickysolo
