### ISSUE TITLE
Logo más grande

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/welcome.osweekends.com#2]
@ValKiriann ... ¿Podrías mejorar el formato de [este logo](https://github.com/OSWeekends/welcome.osweekends.com/blob/gh-pages/assets/images/illos/osw.svg) para tener una proporción similar al resto de la misma carpeta y con el fondo transparente?

**Muchas gracias!**

**Comment by ValKiriann** [comment]
allá que voy
