### ISSUE TITLE
Comportamiento del titulo (OSW)

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/welcome.osweekends.com#20]
En `http://localhost:9000/sobre-open-source-weekends.html` al hacer click en el boton de OSW (arriba centrado) nos lleva al index. En el resto de páginas no. Revisar y unificar comportamiento del link.

![image](https://user-images.githubusercontent.com/5422102/35994891-1350adc2-0d12-11e8-98be-19eecd6180a4.png)

**Comment by Vickysolo** [comment]
Arreglado :)
